### ISSUE TITLE
PHP Fatal error: Call to a member function getExtensionAttributes

### ISSUE THREAD

**Issue by martijn-bigbridge** [tig-nl/postcode-magento2#9]
We found fatal errors in the php logfile.

```
[11-Dec-2018 23:11:13 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getExtensionAttributes() on null in /sitepath/vendor/tig/postcode-magento2/Plugin/Address/Management/GuestPayment.php:68
Stack trace:
#0 /sitepath/vendor/magento/framework/Interception/Interceptor.php(121): TIG\Postcode\Plugin\Address\Management\GuestPayment->beforeSavePaymentInformation(Object(Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor), 'afasdfsfsefa...', 'afewfef@sfsdf...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), NULL)
#1 /sitepath/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\GuestPaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}('afasdfsfsefa...', 'afewfef@sfsdf...', Object(Magento\Quote\Model\Quote\Payment\Interceptor), NULL)
#2 /var/domain in /sitepath/vendor/tig/postcode-magento2/Plugin/Address/Management/GuestPayment.php on line 68
```

\TIG\Postcode\Plugin\Address\Management\GuestPayment::beforeSavePaymentInformation
```
$attributes = $billingAddress->getExtensionAttributes();
        if (empty($attributes)) {
            return [$cartId, $email, $paymentMethod, $billingAddress];
        }
```
Maybe its better to check if billingAddress is not null and have ExtensionAttributes.

**Comment by tig-rikjonkmans** [comment]
Hi @martijn-bigbridge ,

May i ask which checkout you are using ?

**Comment by martijn-bigbridge** [comment]
Hi @tig-rikjonkmans 
https://amasty.com/one-step-checkout-for-magento-2.html

**Comment by tig-rikjonkmans** [comment]
Hi @martijn-bigbridge ,

We shall add validation to this method like you mentioned. 
I should also mention that we are currently working on the 1.2 version which contains more compatible fixes for Amasty. 

Thanks for reporting this issue.

**Comment by martijn-bigbridge** [comment]
Oke thanks !
